### ISSUE TITLE
Sync plugin shows negative duration

### ISSUE THREAD

**Issue by tnozicka** [openshift/jenkins-sync-plugin#107]
It happens quite often that I see stages with negative duration. It looks pretty bad in OpenShift Console to see such stage took **-5m**. It seems already wrong in `metadata.annotations."openshift.io/jenkins-status-json"` so I am thinking this is about sync plugin. (**durationMillis** shall not be **negative**; same for **pauseDurationMillis**)

```json
        {
            "_links": {
                "self": {
                    "href": "https://jenkins-myproject.172.16.20.10.xip.io/job/nodejs-ex-pipeline/1/execution/node/21/wfapi/describe"
                }
            },
            "id": "21",
            "name": "Integration Tests",
            "execNode": "",
            "status": "SUCCESS",
            "startTimeMillis": 1479212527464,
            "durationMillis": -158445,
            "pauseDurationMillis": -158445,
            "stageFlowNodes": [
                {
                    "_links": {
                        "self": {
                            "href": "https://jenkins-myproject.172.16.20.10.xip.io/job/nodejs-ex-pipeline/1/execution/node/22/wfapi/describe"
                        }
                    },
                    "id": "22",
                    "name": "Shell Script",
                    "execNode": "",
                    "status": "SUCCESS",
                    "startTimeMillis": 1479212527520,
                    "durationMillis": 14578,
                    "pauseDurationMillis": 0,
                    "parentNodes": [
                        "21"
                    ]
                },
                {
                    "_links": {
                        "self": {
                            "href": "https://jenkins-myproject.172.16.20.10.xip.io/job/nodejs-ex-pipeline/1/execution/node/23/wfapi/describe"
                        }
                    },
                    "id": "23",
                    "name": "Shell Script",
                    "execNode": "",
                    "status": "SUCCESS",
                    "startTimeMillis": 1479212542098,
                    "durationMillis": 1129,
                    "pauseDurationMillis": 0,
                    "parentNodes": [
                        "22"
                    ]
                },
                {
                    "_links": {
                        "self": {
                            "href": "https://jenkins-myproject.172.16.20.10.xip.io/job/nodejs-ex-pipeline/1/execution/node/24/wfapi/describe"
                        }
                    },
                    "id": "24",
                    "name": "Archive artifacts",
                    "execNode": "",
                    "status": "SUCCESS",
                    "startTimeMillis": 1479212543227,
                    "durationMillis": 1049,
                    "pauseDurationMillis": 0,
                    "parentNodes": [
                        "23"
                    ]
                },
                {
                    "_links": {
                        "self": {
                            "href": "https://jenkins-myproject.172.16.20.10.xip.io/job/nodejs-ex-pipeline/1/execution/node/25/wfapi/describe"
                        }
                    },
                    "id": "25",
                    "name": "General Build Step",
                    "execNode": "",
                    "status": "SUCCESS",
                    "startTimeMillis": 1479212544276,
                    "durationMillis": 2698,
                    "pauseDurationMillis": 0,
                    "parentNodes": [
                        "24"
                    ]
                }
            ]
        }

```

**Comment by jimmidyson** [comment]
That's really interesting. The content of that comes straight from Jenkins (https://github.com/jenkinsci/openshift-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java#L187) , unchanged (apart from updating the href to be the discovered external URL). This looks like a bug in Jenkins pipeline plugin instead.

**Comment by bparees** [comment]
@tnozicka have you seen this lately?  i haven't heard anyone else report it in a while.

**Comment by tnozicka** [comment]
@bparees I didn't have a chance to use pipelines for quite some time. If nobody else is seeing it, it might got fixed in upstream plugin. I am ok with reopening it if I bump into it again.

**Comment by bparees** [comment]
sounds good, thanks @tnozicka

**Comment by battlesnake** [comment]
Years later, but FYI in case the issue is still present for your users - I also see negative durations from Jenkins sometimes, when querying the Jenkins API directly (not using openshift).
